In [13]:
import numpy as np
scores = np.random.randint(1,9,(4,5))
y = np.random.randint(0,5,(4,1))
print(scores)
print(y)

[[5 2 7 2 3]
 [8 5 3 7 3]
 [4 2 4 5 6]
 [1 8 7 1 6]]
[[3]
 [0]
 [0]
 [2]]


In [40]:
print(np.arange(5))
correct_scores = []
for i in range(4):
    correct_scores.append(scores[i,y[i]][0])
correct_scores = np.array(correct_scores).reshape(4,1)
print(correct_scores)
margins = scores - correct_scores + 1
print(margins)
    


[0 1 2 3 4]
[[2]
 [8]
 [4]
 [7]]
[[ 4  1  6  1  2]
 [ 1 -2 -4  0 -4]
 [ 1 -1  1  2  3]
 [-5  2  1 -5  0]]


In [45]:
margins[margins < 0] = 0
print(margins)
loss = np.sum(margins)
print(loss)
    

[[4 1 6 1 2]
 [1 0 0 0 0]
 [1 0 1 2 3]
 [0 2 1 0 0]]
[14  1  7  3]


In [4]:
def fun(a,b):
    print(a+b)
fun2 = lambda x:fun(x,5)[0]
c = map(fun2,[1,2,3])
print(list(c))

6


TypeError: 'NoneType' object is not subscriptable

In [14]:
a = []
for i in range(5):
    if i == 2:
        continue
    a.append(i)
print(a)

[0, 1, 3, 4]
